/**
 * 名称汉化内置词典(主流球队/国家队/知名教练,准确译名);
 * 词典未命中走 name_zh 表(LLM 音译缓存),再未命中显示原名。
 */
export const NAMES_ZH: Record<string, string> = {
  // ── 英超 ──
  "Manchester City": "曼城", "Man City": "曼城", "Arsenal": "阿森纳", "Liverpool": "利物浦",
  "Manchester United": "曼联", "Man United": "曼联", "Chelsea": "切尔西", "Tottenham": "热刺",
  "Tottenham Hotspur": "热刺", "Spurs": "热刺", "Newcastle": "纽卡斯尔", "Newcastle United": "纽卡斯尔",
  "Aston Villa": "阿斯顿维拉", "West Ham": "西汉姆联", "West Ham United": "西汉姆联",
  "Brighton": "布莱顿", "Wolves": "狼队", "Wolverhampton Wanderers": "狼队",
  "Everton": "埃弗顿", "Fulham": "富勒姆", "Brentford": "布伦特福德", "Crystal Palace": "水晶宫",
  "Nottingham Forest": "诺丁汉森林", "Bournemouth": "伯恩茅斯", "Leicester": "莱斯特城",
  "Leicester City": "莱斯特城", "Leeds": "利兹联", "Leeds United": "利兹联", "Southampton": "南安普顿",
  "Ipswich": "伊普斯维奇", "Ipswich Town": "伊普斯维奇", "Burnley": "伯恩利", "Sunderland": "桑德兰",
  // ── 西甲 ──
  "Real Madrid": "皇家马德里", "Barcelona": "巴塞罗那", "Atletico Madrid": "马德里竞技",
  "Athletic Club": "毕尔巴鄂竞技", "Athletic Bilbao": "毕尔巴鄂竞技", "Real Sociedad": "皇家社会",
  "Villarreal": "比利亚雷亚尔", "Real Betis": "皇家贝蒂斯", "Sevilla": "塞维利亚",
  "Valencia": "瓦伦西亚", "Girona": "赫罗纳", "Osasuna": "奥萨苏纳", "Celta Vigo": "塞尔塔",
  "Rayo Vallecano": "巴列卡诺", "Mallorca": "马略卡", "Getafe": "赫塔费", "Alaves": "阿拉维斯",
  "Espanyol": "西班牙人", "Las Palmas": "拉斯帕尔马斯", "Real Valladolid": "巴利亚多利德",
  // ── 德甲 ──
  "Bayern Munich": "拜仁慕尼黑", "Bayern München": "拜仁慕尼黑", "Borussia Dortmund": "多特蒙德",
  "Bayer Leverkusen": "勒沃库森", "RB Leipzig": "莱比锡红牛", "Eintracht Frankfurt": "法兰克福",
  "VfB Stuttgart": "斯图加特", "Borussia Monchengladbach": "门兴格拉德巴赫",
  "Borussia Mönchengladbach": "门兴格拉德巴赫", "VfL Wolfsburg": "沃尔夫斯堡", "SC Freiburg": "弗赖堡",
  "TSG Hoffenheim": "霍芬海姆", "1899 Hoffenheim": "霍芬海姆", "Werder Bremen": "云达不来梅",
  "FC Augsburg": "奥格斯堡", "Union Berlin": "柏林联合", "1. FC Union Berlin": "柏林联合",
  "Mainz 05": "美因茨", "FSV Mainz 05": "美因茨", "FC St. Pauli": "圣保利", "Holstein Kiel": "基尔",
  "1. FC Heidenheim": "海登海姆", "VfL Bochum": "波鸿", "FC Koln": "科隆", "1. FC Köln": "科隆",
  "Hamburger SV": "汉堡",
  // ── 意甲 ──
  "Inter": "国际米兰", "Inter Milan": "国际米兰", "AC Milan": "AC米兰", "Milan": "AC米兰",
  "Juventus": "尤文图斯", "Napoli": "那不勒斯", "AS Roma": "罗马", "Roma": "罗马",
  "Lazio": "拉齐奥", "Atalanta": "亚特兰大", "Fiorentina": "佛罗伦萨", "Bologna": "博洛尼亚",
  "Torino": "都灵", "Udinese": "乌迪内斯", "Genoa": "热那亚", "Cagliari": "卡利亚里",
  "Verona": "维罗纳", "Hellas Verona": "维罗纳", "Empoli": "恩波利", "Parma": "帕尔马",
  "Lecce": "莱切", "Como": "科莫", "Monza": "蒙扎", "Venezia": "威尼斯", "Sassuolo": "萨索洛",
  "Pisa": "比萨", "Cremonese": "克雷莫纳",
  // ── 法甲 ──
  "Paris Saint Germain": "巴黎圣日耳曼", "Paris Saint-Germain": "巴黎圣日耳曼", "PSG": "巴黎圣日耳曼",
  "Marseille": "马赛", "Olympique Marseille": "马赛", "Lyon": "里昂", "Olympique Lyonnais": "里昂",
  "Monaco": "摩纳哥", "AS Monaco": "摩纳哥", "Lille": "里尔", "LOSC Lille": "里尔",
  "Nice": "尼斯", "OGC Nice": "尼斯", "Lens": "朗斯", "RC Lens": "朗斯", "Rennes": "雷恩",
  "Stade Rennais": "雷恩", "Strasbourg": "斯特拉斯堡", "Toulouse": "图卢兹", "Nantes": "南特",
  "Reims": "兰斯", "Stade de Reims": "兰斯", "Montpellier": "蒙彼利埃", "Brest": "布雷斯特",
  "Stade Brestois 29": "布雷斯特", "Le Havre": "勒阿弗尔", "Auxerre": "欧塞尔", "Angers": "昂热",
  "Saint-Etienne": "圣埃蒂安", "AS Saint-Etienne": "圣埃蒂安",
  // ── 欧战常客 ──
  "Porto": "波尔图", "FC Porto": "波尔图", "Benfica": "本菲卡", "Sporting CP": "里斯本竞技",
  "Ajax": "阿贾克斯", "PSV Eindhoven": "PSV埃因霍温", "PSV": "PSV埃因霍温", "Feyenoord": "费耶诺德",
  "Celtic": "凯尔特人", "Rangers": "流浪者", "Galatasaray": "加拉塔萨雷", "Fenerbahce": "费内巴切",
  "Besiktas": "贝西克塔斯", "Shakhtar Donetsk": "顿涅茨克矿工", "Red Bull Salzburg": "萨尔茨堡红牛",
  "Club Brugge": "布鲁日", "Club Brugge KV": "布鲁日", "Anderlecht": "安德莱赫特",
  "Olympiakos": "奥林匹亚科斯", "Olympiakos Piraeus": "奥林匹亚科斯", "Copenhagen": "哥本哈根",
  "Young Boys": "伯尔尼年轻人", "Slavia Praha": "布拉格斯拉维亚", "Sparta Praha": "布拉格斯巴达",
  // ── 国家队(世界杯)──
  "Argentina": "阿根廷", "Brazil": "巴西", "France": "法国", "England": "英格兰", "Spain": "西班牙",
  "Germany": "德国", "Italy": "意大利", "Portugal": "葡萄牙", "Netherlands": "荷兰", "Belgium": "比利时",
  "Croatia": "克罗地亚", "Uruguay": "乌拉圭", "Colombia": "哥伦比亚", "Mexico": "墨西哥",
  "USA": "美国", "United States": "美国", "Canada": "加拿大", "Japan": "日本", "South Korea": "韩国",
  "Korea Republic": "韩国", "Australia": "澳大利亚", "Saudi Arabia": "沙特阿拉伯", "Iran": "伊朗",
  "Qatar": "卡塔尔", "Morocco": "摩洛哥", "Senegal": "塞内加尔", "Ghana": "加纳", "Nigeria": "尼日利亚",
  "Cameroon": "喀麦隆", "Tunisia": "突尼斯", "Algeria": "阿尔及利亚", "Egypt": "埃及",
  "South Africa": "南非", "Ivory Coast": "科特迪瓦", "Cote d'Ivoire": "科特迪瓦",
  "Switzerland": "瑞士", "Austria": "奥地利", "Poland": "波兰", "Denmark": "丹麦", "Sweden": "瑞典",
  "Norway": "挪威", "Scotland": "苏格兰", "Wales": "威尔士", "Serbia": "塞尔维亚", "Turkey": "土耳其",
  "Türkiye": "土耳其", "Ukraine": "乌克兰", "Czech Republic": "捷克", "Czechia": "捷克",
  "Greece": "希腊", "Romania": "罗马尼亚", "Hungary": "匈牙利", "Slovakia": "斯洛伐克",
  "Slovenia": "斯洛文尼亚", "Albania": "阿尔巴尼亚", "Georgia": "格鲁吉亚", "Ecuador": "厄瓜多尔",
  "Peru": "秘鲁", "Chile": "智利", "Paraguay": "巴拉圭", "Venezuela": "委内瑞拉", "Bolivia": "玻利维亚",
  "Panama": "巴拿马", "Costa Rica": "哥斯达黎加", "Honduras": "洪都拉斯", "Jamaica": "牙买加",
  "New Zealand": "新西兰", "China": "中国", "China PR": "中国", "Indonesia": "印度尼西亚",
  "Thailand": "泰国", "Vietnam": "越南", "Iraq": "伊拉克", "UAE": "阿联酋", "Jordan": "约旦",
  "Uzbekistan": "乌兹别克斯坦",
  // ── 知名球员(常见拼写;冷门球员由 LLM 音译队列补齐)──
  "E. Haaland": "哈兰德", "Erling Haaland": "哈兰德", "K. De Bruyne": "德布劳内", "Kevin De Bruyne": "德布劳内",
  "Rodri": "罗德里", "Phil Foden": "福登", "P. Foden": "福登", "B. Silva": "贝尔纳多·席尔瓦", "Bernardo Silva": "贝尔纳多·席尔瓦",
  "Ederson": "埃德森", "K. Walker": "沃克", "Kyle Walker": "沃克", "R. Dias": "鲁本·迪亚斯", "Rúben Dias": "鲁本·迪亚斯",
  "B. Saka": "萨卡", "Bukayo Saka": "萨卡", "M. Ødegaard": "厄德高", "Martin Ødegaard": "厄德高", "M. Odegaard": "厄德高",
  "D. Rice": "赖斯", "Declan Rice": "赖斯", "G. Jesus": "热苏斯", "Gabriel Jesus": "热苏斯", "K. Havertz": "哈弗茨",
  "Kai Havertz": "哈弗茨", "W. Saliba": "萨利巴", "William Saliba": "萨利巴", "G. Martinelli": "马丁内利",
  "M. Salah": "萨拉赫", "Mohamed Salah": "萨拉赫", "V. van Dijk": "范戴克", "Virgil van Dijk": "范戴克",
  "Alisson": "阿利松", "Alisson Becker": "阿利松", "L. Díaz": "路易斯·迪亚斯", "Luis Díaz": "路易斯·迪亚斯",
  "D. Szoboszlai": "索博斯洛伊", "C. Gakpo": "加克波", "Cody Gakpo": "加克波", "A. Mac Allister": "麦卡利斯特",
  "Alexis Mac Allister": "麦卡利斯特", "T. Alexander-Arnold": "阿诺德", "Trent Alexander-Arnold": "阿诺德",
  "C. Palmer": "帕尔默", "Cole Palmer": "帕尔默", "N. Jackson": "尼古拉斯·杰克逊", "E. Fernández": "恩佐·费尔南德斯",
  "Enzo Fernández": "恩佐·费尔南德斯", "M. Caicedo": "凯塞多", "Moisés Caicedo": "凯塞多", "R. James": "里斯·詹姆斯",
  "B. Fernandes": "B费尔南德斯", "Bruno Fernandes": "B费尔南德斯", "M. Rashford": "拉什福德", "Marcus Rashford": "拉什福德",
  "A. Onana": "奥纳纳", "K. Mainoo": "梅努", "Kobbie Mainoo": "梅努", "R. Højlund": "霍伊伦", "Rasmus Højlund": "霍伊伦",
  "H. Kane": "凯恩", "Harry Kane": "凯恩", "Son Heung-Min": "孙兴慜", "H. Son": "孙兴慜", "J. Maddison": "麦迪逊",
  "James Maddison": "麦迪逊", "C. Romero": "罗梅罗", "Cristian Romero": "罗梅罗",
  "A. Isak": "伊萨克", "Alexander Isak": "伊萨克", "B. Guimarães": "吉马良斯", "Bruno Guimarães": "吉马良斯",
  "K. Mbappé": "姆巴佩", "Kylian Mbappé": "姆巴佩", "K. Mbappe": "姆巴佩", "Vinícius Júnior": "维尼修斯",
  "Vini Jr.": "维尼修斯", "Vinicius Junior": "维尼修斯", "J. Bellingham": "贝林厄姆", "Jude Bellingham": "贝林厄姆",
  "Rodrygo": "罗德里戈", "F. Valverde": "巴尔韦德", "Federico Valverde": "巴尔韦德", "T. Courtois": "库尔图瓦",
  "Thibaut Courtois": "库尔图瓦", "A. Rüdiger": "吕迪格", "Antonio Rüdiger": "吕迪格", "E. Camavinga": "卡马文加",
  "A. Tchouaméni": "琼阿梅尼", "L. Modrić": "莫德里奇", "Luka Modrić": "莫德里奇", "D. Carvajal": "卡瓦哈尔",
  "R. Lewandowski": "莱万多夫斯基", "Robert Lewandowski": "莱万多夫斯基", "Lamine Yamal": "亚马尔",
  "Pedri": "佩德里", "Gavi": "加维", "F. de Jong": "德容", "Frenkie de Jong": "德容", "Raphinha": "拉菲尼亚",
  "M. ter Stegen": "特尔施特根", "Marc-André ter Stegen": "特尔施特根", "J. Koundé": "孔德", "Jules Koundé": "孔德",
  "A. Griezmann": "格列兹曼", "Antoine Griezmann": "格列兹曼", "J. Álvarez": "阿尔瓦雷斯", "Julián Álvarez": "阿尔瓦雷斯",
  "J. Oblak": "奥布拉克", "Jan Oblak": "奥布拉克", "K. Llorente": "略伦特",
  "H. Kane (Bayern)": "凯恩", "J. Musiala": "穆夏拉", "Jamal Musiala": "穆夏拉", "L. Sané": "萨内", "Leroy Sané": "萨内",
  "M. Neuer": "诺伊尔", "Manuel Neuer": "诺伊尔", "J. Kimmich": "基米希", "Joshua Kimmich": "基米希",
  "A. Davies": "阿方索·戴维斯", "Alphonso Davies": "阿方索·戴维斯", "T. Müller": "穆勒", "Thomas Müller": "穆勒",
  "F. Wirtz": "维尔茨", "Florian Wirtz": "维尔茨", "V. Boniface": "博尼法斯", "Victor Boniface": "博尼法斯",
  "G. Xhaka": "扎卡", "Granit Xhaka": "扎卡", "J. Frimpong": "弗林蓬", "Jeremie Frimpong": "弗林蓬",
  "S. Gnabry": "格纳布里", "K. Coman": "科曼", "Kingsley Coman": "科曼", "N. Füllkrug": "菲尔克鲁格",
  "M. Reus": "罗伊斯", "Marco Reus": "罗伊斯", "G. Kobel": "科贝尔", "Gregor Kobel": "科贝尔",
  "L. Martínez": "劳塔罗·马丁内斯", "Lautaro Martínez": "劳塔罗·马丁内斯", "M. Thuram": "图拉姆",
  "Marcus Thuram": "图拉姆", "N. Barella": "巴雷拉", "Nicolò Barella": "巴雷拉", "H. Çalhanoğlu": "恰尔汗奥卢",
  "Hakan Çalhanoğlu": "恰尔汗奥卢", "Y. Sommer": "索默", "Yann Sommer": "索默", "A. Bastoni": "巴斯托尼",
  "R. Leão": "莱奥", "Rafael Leão": "莱奥", "C. Pulisic": "普利西奇", "Christian Pulisic": "普利西奇",
  "T. Hernández": "特奥", "Theo Hernández": "特奥", "M. Maignan": "迈尼昂", "Mike Maignan": "迈尼昂",
  "O. Giroud": "吉鲁", "Olivier Giroud": "吉鲁", "D. Vlahović": "弗拉霍维奇", "Dušan Vlahović": "弗拉霍维奇",
  "F. Chiesa": "基耶萨", "Federico Chiesa": "基耶萨", "V. Osimhen": "奥斯梅恩", "Victor Osimhen": "奥斯梅恩",
  "K. Kvaratskhelia": "克瓦拉茨赫利亚", "Khvicha Kvaratskhelia": "克瓦拉茨赫利亚", "P. Dybala": "迪巴拉",
  "Paulo Dybala": "迪巴拉", "R. Lukaku": "卢卡库", "Romelu Lukaku": "卢卡库",
  "O. Dembélé": "登贝莱", "Ousmane Dembélé": "登贝莱", "Marquinhos": "马尔基尼奥斯", "A. Hakimi": "阿什拉夫",
  "Achraf Hakimi": "阿什拉夫", "G. Donnarumma": "多纳鲁马", "Gianluigi Donnarumma": "多纳鲁马",
  "Vitinha": "维蒂尼亚", "Bradley Barcola": "巴尔科拉", "Lionel Messi": "梅西", "L. Messi": "梅西",
  "Cristiano Ronaldo": "C罗", "Neymar": "内马尔", "Neymar Jr": "内马尔", "K. Benzema": "本泽马",
  "Karim Benzema": "本泽马", "S. Mané": "马内", "Sadio Mané": "马内",
  // 裸姓常用形式(音译一致,无歧义风险)
  "Haaland": "哈兰德", "Foden": "福登", "Walker": "沃克", "Akanji": "阿坎吉", "Gvardiol": "格瓦迪奥尔",
  "Kovacic": "科瓦契奇", "De Bruyne": "德布劳内", "Grealish": "格拉利什", "Stones": "斯通斯",
  "Saka": "萨卡", "Rice": "赖斯", "Saliba": "萨利巴", "Timber": "廷贝尔", "White": "本·怀特",
  "Raya": "拉亚", "Odegaard": "厄德高", "Havertz": "哈弗茨", "Trossard": "特罗萨德", "Martinelli": "马丁内利",
  "Salah": "萨拉赫", "Szoboszlai": "索博斯洛伊", "Konate": "科纳特", "Robertson": "罗伯逊", "Gakpo": "加克波",
  "Bellingham": "贝林厄姆", "Valverde": "巴尔韦德", "Courtois": "库尔图瓦", "Rudiger": "吕迪格",
  "Camavinga": "卡马文加", "Tchouameni": "琼阿梅尼", "Carvajal": "卡瓦哈尔", "Mbappe": "姆巴佩",
  "Lewandowski": "莱万多夫斯基", "Pedri": "佩德里", "Yamal": "亚马尔", "Kounde": "孔德", "Balde": "巴尔德",
  "Kane": "凯恩", "Musiala": "穆夏拉", "Kimmich": "基米希", "Sane": "萨内", "Neuer": "诺伊尔",
  "Wirtz": "维尔茨", "Xhaka": "扎卡", "Maddison": "麦迪逊", "Romero": "罗梅罗", "Isak": "伊萨克",
  "Barella": "巴雷拉", "Bastoni": "巴斯托尼", "Thuram": "图拉姆", "Leao": "莱奥", "Maignan": "迈尼昂",
  "Pulisic": "普利西奇", "Vlahovic": "弗拉霍维奇", "Osimhen": "奥斯梅恩", "Dybala": "迪巴拉", "Lukaku": "卢卡库",
  "Dembele": "登贝莱", "Hakimi": "阿什拉夫", "Donnarumma": "多纳鲁马", "Griezmann": "格列兹曼", "Oblak": "奥布拉克",
  "Messi": "梅西", "Ronaldo": "C罗", "Benzema": "本泽马", "Modric": "莫德里奇", "Casemiro": "卡塞米罗",
  "Fernandes": "B费尔南德斯", "Rashford": "拉什福德", "Onana": "奥纳纳", "Mainoo": "梅努", "Hojlund": "霍伊伦",
  "Palmer": "帕尔默", "Caicedo": "凯塞多", "Jackson": "尼古拉斯·杰克逊", "Mudryk": "穆德里克",
  // ── 知名教练 ──
  "Pep Guardiola": "瓜迪奥拉", "Guardiola": "瓜迪奥拉", "Mikel Arteta": "阿尔特塔",
  "Jurgen Klopp": "克洛普", "Carlo Ancelotti": "安切洛蒂", "Xabi Alonso": "哈维·阿隆索",
  "Hansi Flick": "弗里克", "Diego Simeone": "西蒙尼", "Luis Enrique": "恩里克",
  "Erik ten Hag": "滕哈赫", "Unai Emery": "埃梅里", "Ange Postecoglou": "波斯特科格鲁",
  "Thomas Tuchel": "图赫尔", "Jose Mourinho": "穆里尼奥", "Antonio Conte": "孔蒂",
  "Massimiliano Allegri": "阿莱格里", "Simone Inzaghi": "小因扎吉", "Gian Piero Gasperini": "加斯佩里尼",
  "Lionel Scaloni": "斯卡洛尼", "Didier Deschamps": "德尚", "Gareth Southgate": "索斯盖特",
  "Julian Nagelsmann": "纳格尔斯曼", "Roberto Martinez": "罗伯托·马丁内斯",
};
