/**
 * 名称汉化内置词典(主流球队/国家队/知名教练,准确译名);
 * 词典未命中走 name_zh 表(LLM 音译缓存),再未命中显示原名。
 */
export const NAMES_ZH: Record<string, string> = {
  // ── 英超 ──
  "Manchester City": "曼城", "Man City": "曼城", "Arsenal": "阿森纳", "Liverpool": "利物浦",
  "Manchester United": "曼联", "Man United": "曼联", "Chelsea": "切尔西", "Tottenham": "热刺",
  "Tottenham Hotspur": "热刺", "Spurs": "热刺", "Newcastle": "纽卡斯尔", "Newcastle United": "纽卡斯尔",
  "Aston Villa": "阿斯顿维拉", "West Ham": "西汉姆联", "West Ham United": "西汉姆联",
  "Brighton": "布莱顿", "Wolves": "狼队", "Wolverhampton Wanderers": "狼队",
  "Everton": "埃弗顿", "Fulham": "富勒姆", "Brentford": "布伦特福德", "Crystal Palace": "水晶宫",
  "Nottingham Forest": "诺丁汉森林", "Bournemouth": "伯恩茅斯", "Leicester": "莱斯特城",
  "Leicester City": "莱斯特城", "Leeds": "利兹联", "Leeds United": "利兹联", "Southampton": "南安普顿",
  "Ipswich": "伊普斯维奇", "Ipswich Town": "伊普斯维奇", "Burnley": "伯恩利", "Sunderland": "桑德兰",
  // ── 西甲 ──
  "Real Madrid": "皇家马德里", "Barcelona": "巴塞罗那", "Atletico Madrid": "马德里竞技",
  "Athletic Club": "毕尔巴鄂竞技", "Athletic Bilbao": "毕尔巴鄂竞技", "Real Sociedad": "皇家社会",
  "Villarreal": "比利亚雷亚尔", "Real Betis": "皇家贝蒂斯", "Sevilla": "塞维利亚",
  "Valencia": "瓦伦西亚", "Girona": "赫罗纳", "Osasuna": "奥萨苏纳", "Celta Vigo": "塞尔塔",
  "Rayo Vallecano": "巴列卡诺", "Mallorca": "马略卡", "Getafe": "赫塔费", "Alaves": "阿拉维斯",
  "Espanyol": "西班牙人", "Las Palmas": "拉斯帕尔马斯", "Real Valladolid": "巴利亚多利德",
  // ── 德甲 ──
  "Bayern Munich": "拜仁慕尼黑", "Bayern München": "拜仁慕尼黑", "Borussia Dortmund": "多特蒙德",
  "Bayer Leverkusen": "勒沃库森", "RB Leipzig": "莱比锡红牛", "Eintracht Frankfurt": "法兰克福",
  "VfB Stuttgart": "斯图加特", "Borussia Monchengladbach": "门兴格拉德巴赫",
  "Borussia Mönchengladbach": "门兴格拉德巴赫", "VfL Wolfsburg": "沃尔夫斯堡", "SC Freiburg": "弗赖堡",
  "TSG Hoffenheim": "霍芬海姆", "1899 Hoffenheim": "霍芬海姆", "Werder Bremen": "云达不来梅",
  "FC Augsburg": "奥格斯堡", "Union Berlin": "柏林联合", "1. FC Union Berlin": "柏林联合",
  "Mainz 05": "美因茨", "FSV Mainz 05": "美因茨", "FC St. Pauli": "圣保利", "Holstein Kiel": "基尔",
  "1. FC Heidenheim": "海登海姆", "VfL Bochum": "波鸿", "FC Koln": "科隆", "1. FC Köln": "科隆",
  "Hamburger SV": "汉堡",
  // ── 意甲 ──
  "Inter": "国际米兰", "Inter Milan": "国际米兰", "AC Milan": "AC米兰", "Milan": "AC米兰",
  "Juventus": "尤文图斯", "Napoli": "那不勒斯", "AS Roma": "罗马", "Roma": "罗马",
  "Lazio": "拉齐奥", "Atalanta": "亚特兰大", "Fiorentina": "佛罗伦萨", "Bologna": "博洛尼亚",
  "Torino": "都灵", "Udinese": "乌迪内斯", "Genoa": "热那亚", "Cagliari": "卡利亚里",
  "Verona": "维罗纳", "Hellas Verona": "维罗纳", "Empoli": "恩波利", "Parma": "帕尔马",
  "Lecce": "莱切", "Como": "科莫", "Monza": "蒙扎", "Venezia": "威尼斯", "Sassuolo": "萨索洛",
  "Pisa": "比萨", "Cremonese": "克雷莫纳",
  // ── 法甲 ──
  "Paris Saint Germain": "巴黎圣日耳曼", "Paris Saint-Germain": "巴黎圣日耳曼", "PSG": "巴黎圣日耳曼",
  "Marseille": "马赛", "Olympique Marseille": "马赛", "Lyon": "里昂", "Olympique Lyonnais": "里昂",
  "Monaco": "摩纳哥", "AS Monaco": "摩纳哥", "Lille": "里尔", "LOSC Lille": "里尔",
  "Nice": "尼斯", "OGC Nice": "尼斯", "Lens": "朗斯", "RC Lens": "朗斯", "Rennes": "雷恩",
  "Stade Rennais": "雷恩", "Strasbourg": "斯特拉斯堡", "Toulouse": "图卢兹", "Nantes": "南特",
  "Reims": "兰斯", "Stade de Reims": "兰斯", "Montpellier": "蒙彼利埃", "Brest": "布雷斯特",
  "Stade Brestois 29": "布雷斯特", "Le Havre": "勒阿弗尔", "Auxerre": "欧塞尔", "Angers": "昂热",
  "Saint-Etienne": "圣埃蒂安", "AS Saint-Etienne": "圣埃蒂安",
  // ── 欧战常客 ──
  "Porto": "波尔图", "FC Porto": "波尔图", "Benfica": "本菲卡", "Sporting CP": "里斯本竞技",
  "Ajax": "阿贾克斯", "PSV Eindhoven": "PSV埃因霍温", "PSV": "PSV埃因霍温", "Feyenoord": "费耶诺德",
  "Celtic": "凯尔特人", "Rangers": "流浪者", "Galatasaray": "加拉塔萨雷", "Fenerbahce": "费内巴切",
  "Besiktas": "贝西克塔斯", "Shakhtar Donetsk": "顿涅茨克矿工", "Red Bull Salzburg": "萨尔茨堡红牛",
  "Club Brugge": "布鲁日", "Club Brugge KV": "布鲁日", "Anderlecht": "安德莱赫特",
  "Olympiakos": "奥林匹亚科斯", "Olympiakos Piraeus": "奥林匹亚科斯", "Copenhagen": "哥本哈根",
  "Young Boys": "伯尔尼年轻人", "Slavia Praha": "布拉格斯拉维亚", "Sparta Praha": "布拉格斯巴达",
  // ── 国家队(世界杯)──
  "Argentina": "阿根廷", "Brazil": "巴西", "France": "法国", "England": "英格兰", "Spain": "西班牙",
  "Germany": "德国", "Italy": "意大利", "Portugal": "葡萄牙", "Netherlands": "荷兰", "Belgium": "比利时",
  "Croatia": "克罗地亚", "Uruguay": "乌拉圭", "Colombia": "哥伦比亚", "Mexico": "墨西哥",
  "USA": "美国", "United States": "美国", "Canada": "加拿大", "Japan": "日本", "South Korea": "韩国",
  "Korea Republic": "韩国", "Australia": "澳大利亚", "Saudi Arabia": "沙特阿拉伯", "Iran": "伊朗",
  "Qatar": "卡塔尔", "Morocco": "摩洛哥", "Senegal": "塞内加尔", "Ghana": "加纳", "Nigeria": "尼日利亚",
  "Cameroon": "喀麦隆", "Tunisia": "突尼斯", "Algeria": "阿尔及利亚", "Egypt": "埃及",
  "South Africa": "南非", "Ivory Coast": "科特迪瓦", "Cote d'Ivoire": "科特迪瓦",
  "Switzerland": "瑞士", "Austria": "奥地利", "Poland": "波兰", "Denmark": "丹麦", "Sweden": "瑞典",
  "Norway": "挪威", "Scotland": "苏格兰", "Wales": "威尔士", "Serbia": "塞尔维亚", "Turkey": "土耳其",
  "Türkiye": "土耳其", "Ukraine": "乌克兰", "Czech Republic": "捷克", "Czechia": "捷克",
  "Greece": "希腊", "Romania": "罗马尼亚", "Hungary": "匈牙利", "Slovakia": "斯洛伐克",
  "Slovenia": "斯洛文尼亚", "Albania": "阿尔巴尼亚", "Georgia": "格鲁吉亚", "Ecuador": "厄瓜多尔",
  "Peru": "秘鲁", "Chile": "智利", "Paraguay": "巴拉圭", "Venezuela": "委内瑞拉", "Bolivia": "玻利维亚",
  "Panama": "巴拿马", "Costa Rica": "哥斯达黎加", "Honduras": "洪都拉斯", "Jamaica": "牙买加",
  "New Zealand": "新西兰", "China": "中国", "China PR": "中国", "Indonesia": "印度尼西亚",
  "Thailand": "泰国", "Vietnam": "越南", "Iraq": "伊拉克", "UAE": "阿联酋", "Jordan": "约旦",
  "Uzbekistan": "乌兹别克斯坦",
  // ── 知名教练 ──
  "Pep Guardiola": "瓜迪奥拉", "Guardiola": "瓜迪奥拉", "Mikel Arteta": "阿尔特塔",
  "Jurgen Klopp": "克洛普", "Carlo Ancelotti": "安切洛蒂", "Xabi Alonso": "哈维·阿隆索",
  "Hansi Flick": "弗里克", "Diego Simeone": "西蒙尼", "Luis Enrique": "恩里克",
  "Erik ten Hag": "滕哈赫", "Unai Emery": "埃梅里", "Ange Postecoglou": "波斯特科格鲁",
  "Thomas Tuchel": "图赫尔", "Jose Mourinho": "穆里尼奥", "Antonio Conte": "孔蒂",
  "Massimiliano Allegri": "阿莱格里", "Simone Inzaghi": "小因扎吉", "Gian Piero Gasperini": "加斯佩里尼",
  "Lionel Scaloni": "斯卡洛尼", "Didier Deschamps": "德尚", "Gareth Southgate": "索斯盖特",
  "Julian Nagelsmann": "纳格尔斯曼", "Roberto Martinez": "罗伯托·马丁内斯",
};
