import { chromium } from 'playwright-core';
import chromiumPkg from '@sparticuz/chromium';
const exe = await chromiumPkg.executablePath();
const browser = await chromium.launch({ executablePath: exe, args: chromiumPkg.args, headless: true });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148' });
await ctx.addCookies([{ name: 'pt_sess', value: 'qatok901', domain: 'localhost', path: '/' }]);
const B = 'http://localhost:9712';
const page = await ctx.newPage();
await page.goto(B + '/', { waitUntil: 'networkidle' }); await page.waitForTimeout(500);
await page.getByText('同意', { exact: true }).first().click({ timeout: 3000 }).catch(()=>{});
await page.goto(B + '/data', { waitUntil: 'networkidle' }); await page.waitForTimeout(900);
await page.screenshot({ path: '/tmp/fix-data.png' });
await page.goto(B + '/report/9504', { waitUntil: 'networkidle' }); await page.waitForTimeout(900);
await page.screenshot({ path: '/tmp/fix-report.png' });
await browser.close(); console.log('DONE');
