import { chromium } from 'playwright-core';
import chromiumPkg from '@sparticuz/chromium';
const exe = await chromiumPkg.executablePath();
const browser = await chromium.launch({ executablePath: exe, args: chromiumPkg.args, headless: true });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148' });
await ctx.addCookies([{ name: 'pt_sess', value: 'qatok901', domain: 'localhost', path: '/' }]);
const B = 'http://localhost:9710';
const page = await ctx.newPage();
async function shot(name, path, prep) {
  await page.goto(B + path, { waitUntil: 'networkidle' });
  await page.waitForTimeout(700);
  if (prep) await prep(page).catch(()=>{});
  await page.waitForTimeout(500);
  await page.screenshot({ path: `/tmp/ui-${name}.png`, fullPage: true });
  console.log('shot', name);
}
const tap = (t) => async (p) => { await p.getByText(t, { exact: true }).first().click({ timeout: 3500 }); await p.waitForTimeout(600); };
await shot('01-home-soon', '/');
await shot('02-home-live', '/', tap('直播'));
await shot('03-home-today', '/', tap('今日'));
await shot('04-home-results', '/', tap('赛果'));
await shot('05-detail-odds', '/match/9504');
await shot('06-detail-eu', '/match/9504', tap('欧指'));
await shot('07-detail-match', '/match/9501', tap('赛况'));
await shot('08-detail-squad', '/match/9504', tap('人员'));
await shot('09-detail-deep', '/match/9504', tap('深度'));
await shot('10-moves', '/moves');
await shot('11-predictions', '/predictions');
await shot('12-data-standings', '/data');
await shot('13-data-scorers', '/data', tap('射手'));
await shot('14-report', '/report/9504');
await shot('15-me', '/me');
await shot('16-login', '/login');
await shot('17-faq', '/faq');
await browser.close();
console.log('DONE');
